# Generated by Django 5.1.2 on 2024-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='clik para leer el post', max_length=255),
        ),
    ]
